### ISSUE TITLE
Cannot install extension from vsix file

### ISSUE THREAD

**Issue by eternal-sorrow** [flathub/com.visualstudio.code-oss#1]
I tried to install [this](https://marketplace.visualstudio.com/items?itemName=LaurentTreguier.vscode-simple-icons) icon theme from `.vsix` file, but it does not show up in the installed extensions list. I can definitely see it unpacked in the directory `.var/app/com.visualstudio.code-oss/data/vscode/extensions/laurenttreguier.vscode-simple-icons-1.13.2/`, but it's not listed in the installed extensions nor can I select this icon theme in command palette. Other extensions installed with `.vsix` files are working normally.

**Comment by gasinvein** [comment]
Hm, it didn't show up for me as well at first, but the icon set appeared after relaunch. Can you please try restarting VS Code?

**Comment by eternal-sorrow** [comment]
Of course I tried restarting vscode. Nothing happens. Also, the strange thing: when I install `.vsix` file, vscode shows the notification where it offers to reload vscode to complete installing the extension. I didn't notice it at first but  the notification says "complete installing the extension __EditorConfig for VS Code__". I definitely didn't try to install EditorConfig and I don't have it installed.

**Comment by gasinvein** [comment]
I was unable to reproduce it. How exactly do you install this extension?

**Comment by eternal-sorrow** [comment]
I tried both command line and with GIU. With command line I did this:
```
>flatpak run com.visualstudio.code-oss --install-extension LaurentTreguier.vscode-simple-icons-1.13.2.vsix
flatpak-vscode-oss: Setting up Node.js packages
flatpak-vscode-oss: Setting up Cargo packages
flatpak-vscode-oss: Setting up Python packages
Installing extensions...
Extension 'LaurentTreguier.vscode-simple-icons-1.13.2.vsix' was successfully installed.
```
Nothing unusual, but the extension doesn't show up even after restart.

With GUI I open the extensions sidebar, click on dots menu button (`...`) and select "Install from VSIX...". After that I select the `.vsix` file in file dialog and click "Install" button.

**Comment by gasinvein** [comment]
Weird. I've tried installing it via CLI from embedded terminal (requires restart) and from GUI (becomes available immediately).
Does it even show up in `code-oss --list-extensions` output?

**Comment by eternal-sorrow** [comment]
```
>flatpak run com.visualstudio.code-oss --list-extensions
flatpak-vscode-oss: Setting up Node.js packages
flatpak-vscode-oss: Setting up Cargo packages
flatpak-vscode-oss: Setting up Python packages
ms-python.python
sainnhe.gruvbox-material
```
It does not.

**Comment by gasinvein** [comment]
Nah, I can't reproduce it even in a clean VM. Can you please try with a clean app data dir? E.g. rename `~/.var/app/com.visualstudio.code-oss` before launch, or try with another user/machine.

**Comment by eternal-sorrow** [comment]
Extension installs normally with clean profile. Hmm...

**Comment by gasinvein** [comment]
Did you migrate settings/data from the old `com.visualstudio.code.oss` flatpak, or started using this flatpak from scratch?

**Comment by eternal-sorrow** [comment]
I'm not quite sure. I think I didn't, but I know that I tried installing `com.visualstudio.code.oss` before. I had some issues with it and I noticed that it was unmaintained on flathub, I just removed it. I just don't remember if I removed it's data along with it or not. I think I did, but I'm not sure.

**Comment by eternal-sorrow** [comment]
I tested it more extensively. It does install successfully on the clean profile, but it fails I already installed another extension the same way. For example if I install [this](https://marketplace.visualstudio.com/items?itemName=LaurentTreguier.vscode-simple-icons) one as `.vsix` and then [this](https://marketplace.visualstudio.com/items?itemName=sainnhe.gruvbox-material) one, the second extension installation fails.

**Comment by gasinvein** [comment]
Now I've reproduced it. This looks very similar to VSCodium/vscodium#434

After a quick investigation, I've found that VS Code sometimes writes `__metadata: {}` attribute into extension's `package.json`. If i remove this attribute, extension show up as installed.

**Comment by gasinvein** [comment]
@eternal-sorrow This is said to be fixed on OpenVSX side https://github.com/VSCodium/vscodium/issues/434#issuecomment-658681063
Can you please re-check? You'll likely need to reinstall all .vsix extensions.

**Comment by eternal-sorrow** [comment]
Yes, I tested it on 2 different installations of code-oss, everything works.
