### ISSUE TITLE
No DBus-Connection

### ISSUE THREAD

**Issue by modzilla99** [flathub/com.visualstudio.code-oss#100]
Hey there,

when I tried using the GitLab-Extension it could not write the Authorization information into the Gnome keychain. By enabling the User DBus-Session with Flatseal it now works. I'd appreciate if it could be added by default.

Thank you!

best regards,
modzilla

**Comment by gasinvein** [comment]
It actually needs only the secrets service, not the whole bus. This is an IDE app that is almost unconfined anyway, but in general allowing direct access to the session bus is a bad idea.
Anyway, fixed, thanks for reporting this.

**Comment by modzilla99** [comment]
Ah awesome, great to know thx for the quick fix :)
