### ISSUE TITLE
dotnet not found (from Ubuntu 22.04.1 official repositories)

### ISSUE THREAD

**Issue by FherStk** [flathub/com.visualstudio.code-oss#102]
Hi,

I've just fresh installed an Ubuntu 22.04.1, then installed .NET6 from the official Ubuntu repos (sudo apt install dotnet6) and, finally, I've installed Code-OSS via flatpak (including the dotnet extension). After that, I installed the C# extension by muhammad-sammy, but OmniSharp can't run the "dotnet" command. I also tried to override some environment vars, but nothing works. 

I located the "dotnet" binary under "/run/host/usr/lib/dotnet/dotnet6-6.0.108" but I've got the following error: "/usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./dotnet)"

Any clue about how can I fix this? Thanks a lot in advance.
Fher

**Comment by gasinvein** [comment]
You can't use development tools (or anything, for that matter) from your host OS in a flatpak'ed IDE app. Instead, you can install the tools you need in form of flatpak SDK extensions. E.g. for dotnet, you can install `org.freedesktop.Sdk.Extension.dotnet6`, and then make the app pick it up by setting `FLATPAK_ENABLE_SDK_EXT=dotnet6` environment variable. More exhaustive should've been presented to you on the first launch; run `code-oss /app/share/ide-flatpak-wrapper/first_run.txt` in the builtin terminal to open the readme again.

**Comment by FherStk** [comment]
Great! I didn't realized about the "dodnet6" extenssion and I only tried without the "6". Now i get an error when OmniSharp tries to use the SDK, but I'm sure that it will work well once I change the SDK path using the environment vars. 

Thanks a lot for your help.
