### ISSUE TITLE
Merging effort in packaging OSS version of VSCode

### ISSUE THREAD

**Issue by gbonnefille** [flathub/com.visualstudio.code-oss#19]
What is the difference with https://github.com/flathub/com.vscodium.codium?
What about merging efforts in a single project?

**Comment by gasinvein** [comment]
From the maintainers perspective, primary difference is the build system - VSCodium flatpak repackages it's binaries (from .deb), while this Code OSS flatpak is built from source.
I'm not sure how VSCodium differs from normal VSCode source builds (save for branding), so you should probably ask VSCodium maintainers about it.

**Comment by gbonnefille** [comment]
OK, thanks for comment.

**Comment by gasinvein** [comment]
I believe this question is answered, so closing.

If you have any specific ideas on how we could cooperate with VSCoddium - feel free to reopen and share your thoughts.
