### ISSUE TITLE
Extension host does not start

### ISSUE THREAD

**Issue by alois31** [flathub/com.visualstudio.code-oss#20]
The issue I reported for the proprietary version, https://github.com/flathub/com.visualstudio.code/issues/182, also applies to this open-source build. I believe that including the extension host ipc socket in ```ipc-sockets-path-flatpak.patch``` would solve the issue in this build.

**Comment by gasinvein** [comment]
I'm not quite sure of what Extension host is and what it does. Don't mind to elaborate a bit?

**Comment by gasinvein** [comment]
`/tmp/user/1000/` path looks wierd. What flatpak version do you have? Is `$XDG_RUNTIME_DIR` set in the sandbox?

**Comment by alois31** [comment]
Flatpak version is 1.2.5 from Debian stable. ```$XDG_RUNTIME_DIR``` is set to ```/run/user/1000``` in the sandbox, as it should. Problem is that the socket used by the extension host for some reason uses ```os.tmpdir()``` and not the runtime directory, as seen in line 305 in ```src/vs/base/parts/ipc/node/ipc.net.ts``` (in the vscode source tree).

**Comment by gasinvein** [comment]
I can't find such socket anywhere in my sandbox. How do I make VS Code (try to) create it?

**Comment by alois31** [comment]
That's the problem. The extension host is a process of vscode to support extensions. So if you install any extension, the extension host should start and create the socket. In my case, it cannot create the socket, so it creates the error I see in developer tools and extensions don't work. I'm not sure if the socket is created if you have no extensions.

**Comment by gasinvein** [comment]
Wait, you mean extension don't work at all for you? That's surely not the case for me.

**Comment by alois31** [comment]
Exactly, extensions don't work at all for me. Maybe in your case vscode attempts to create the socket as ```/tmp/vscode-ipc-<uuid>.sock```. I'd argue this is still wrong, but I guess extensions would work in that case.

**Comment by gasinvein** [comment]
No, I have no sockets in `/tmp`, and no sockets like `vscode-ipc-*.sock` are found anywhere.

BTW is `$FLATPAK_ID` set in your sandbox? If not, try setting it manually, e.g. run Code OSS with `flatpak run --env=FLATPAK_ID=com.visualstudio.code-oss com.visualstudio.code-oss`

**Comment by alois31** [comment]
```FLATPAK_ID``` is already set to ```com.visualstudio.code-oss``` for me.

Try opening the developer tools in your code-oss installation (F1, then search for "toggle developer tools" and select that option). Enter the following in the console that appears in the bottom left corner:
```javascript
const os = require('os')
os.tmpdir()
```
You should find the vscode-ipc socket in that directory.

**Comment by gasinvein** [comment]
It's `/tmp`, yet no sockets there. Strange.

**Comment by alois31** [comment]
I just checked in my deb installation of vscode, the socket is not present there either. Apparently it is only used during startup and deleted afterwards. So I guess it's not necessary to use a path shared by multiple instances here. Do you think I should file a bug upstream to use ```XDG_RUNTIME_DIR``` instead (as they already do for some other sockets)?

**Comment by gasinvein** [comment]
The socket should be in `$XDG_RUNTIME_DIR` for sure, but its presence in `/tmp` doesn't explain why do you get `EACCES` error on attempt to listen on it.

**Comment by alois31** [comment]
After some investigations, the error is not actually ```EACCES```. Try the following in a shell on your host (needs nodejs installed, maybe the command is ```node``` on your distro):

    nodejs <<EOF
    const net = require('net')
    let server = net.createServer()
    server.listen('/tmp/nonexistent/test.sock')
    EOF

This also gives the fake ```EACCES``` observed in vscode, but investigation with ```strace``` only shows ```ENOENT``` (and a follow-up ```EBADF```), which I suspect is also the case in the vscode case (as ```/tmp/user/1000``` does not exist inside the sandbox).

**Comment by gasinvein** [comment]
Good finding. But how we end up with `/tmp/user/1000` in the first place?
```ts
export function generateRandomPipeName(): string {
	const randomSuffix = generateUuid();
	if (process.platform === 'win32') {
		return `\\\\.\\pipe\\vscode-ipc-${randomSuffix}-sock`;
	} else {
		// Mac/Unix: use socket file
		return join(tmpdir(), `vscode-ipc-${randomSuffix}.sock`);
	}
}
```
if `os.tmpdir()` returns `/tmp`, this should return `/tmp/vscode-ipc-${randomSuffix}.sock`, shouldn't it? Where does the `user/1000` portion come from?

**Comment by alois31** [comment]
```os.tmpdir()``` returns ```/tmp/user/1000``` here. Apparently, that path leaks from the host environment, but I'm not exactly sure how. ```$TMPDIR``` is not set inside the sandbox (flatpak unsets that, as documented in flatpak-run(1)).

**Comment by gasinvein** [comment]
Looks like an issue worth reporting to flatpak itself. Yet 1.2.5 is rather old, not sure if it's still supported.

**Comment by alois31** [comment]
I think I know what's going wrong now... (from ```lib/os.js``` in the nodejs source tree)
```javascript
function tmpdir() {
  var path;
  if (isWindows) {
    path = process.env.TEMP ||
           process.env.TMP ||
           (process.env.SystemRoot || process.env.windir) + '\\temp';
    if (path.length > 1 && path.endsWith('\\') && !path.endsWith(':\\'))
      path = path.slice(0, -1);
  } else {
    path = safeGetenv('TMPDIR') ||
           safeGetenv('TMP') ||
           safeGetenv('TEMP') ||
           '/tmp';
    if (path.length > 1 && path.endsWith('/'))
      path = path.slice(0, -1);
  }

  return path;
}
```

I don't know how ```TMP``` and ```TEMP``` ended up in there... but if I unset both of these on the host, then code-oss works. I'm still undecided whether that's a bug in nodejs (for relying on ```TMP``` and ```TEMP``` on Linux), flatpak (for not unsetting them) or both.

**Comment by gasinvein** [comment]
So unsetting `TMP` and `TEMP`  is enough to "fix" this?

**Comment by alois31** [comment]
Yes, unsetting TMP and TEMP is enough to paper over the bugs involved here, and makes extensions work correctly in the code-oss flatpak.

**Comment by gasinvein** [comment]
Well, then I consider this somehow resolved. You can unset the vars for the flatpak app with `flatpak override --user --env=TMP= --env=TEMP= com.visualstudio.code-oss`, if needed.
