### ISSUE TITLE
Git fails to push with latest code-oss

### ISSUE THREAD

**Issue by eternal-sorrow** [flathub/com.visualstudio.code-oss#35]
When I try to push (using vscode gui) to ssh remote, I get this error:

```
git push origin master:master
ssh_askpass: exec(/usr/libexec/ssh-askpass): No such file or directory
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Pushing with cli (not in vscode terminal) works fine.

**Comment by gasinvein** [comment]
Does pushing with cli work from the vscode terminal?

**Comment by eternal-sorrow** [comment]
Didn't try it unfortunately. Now I'm not at my working PC where this bug happened.

**Comment by eternal-sorrow** [comment]
Just reproduced this issue on my home PC. And yes, pushing with CLI works from the vscode terminal.

**Comment by gasinvein** [comment]
Weird, I can't reproduce it. Are you pushing to a github repository via https? Is `GIT_ASKPASS` env var set to something different than `/app/main/resources/app/extensions/git/dist/askpass.sh` in the sandbox?

**Comment by eternal-sorrow** [comment]
>Are you pushing to a github repository via https?

Not github and not https. I already said, it's ssh.

**Comment by eternal-sorrow** [comment]
```
echo $GIT_ASKPASS
/app/main/resources/app/extensions/git/dist/askpass.sh
```

In vscode terminal.

**Comment by gasinvein** [comment]
Right, sorry. So it's ssh remote with password auth?

**Comment by eternal-sorrow** [comment]
No, it's key-based auth.

**Comment by gasinvein** [comment]
Hmm, why does it want askpass, then?

**Comment by eternal-sorrow** [comment]
I don't know.
