### ISSUE TITLE
Enable Wayland socket

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/com.visualstudio.code-oss#37]
Visual Studio Code 1.56.0 ships with Electron 12 which supports Wayland. You can launch it by running `flatpak run --socket=wayland com.visualstudio.code-oss --enable-features=UseOzonePlatform --ozone-platform=wayland`.

I don't think there's harm for adding `--socket=wayland` in the manifest. Chrome, Edge and other Chromium based browsers do the same.

**Comment by gasinvein** [comment]
Sure, adding the socket perm won't hurt.
I wonder if we should add a way for the user to customize launch options, similarly to what Chromium flatpak has.

**Comment by TheEvilSkeleton** [comment]
I like the idea.
