### ISSUE TITLE
Flatpak warning is missing

### ISSUE THREAD

**Issue by adambkaplan** [flathub/com.visualstudio.code-oss#4]
Warning test that shows in `com.visualstudio.code` is not present. This is vital for users who run VSCode in a flatpak - most languages need SDK extensions enabled.

https://github.com/flathub/com.visualstudio.code/blob/master/flatpak-warning.txt

**Comment by gasinvein** [comment]
I wonder if we should make the vscode flatpak wrapper shared. There are already 4 or 5 VS Code variations on Flathub (and I guess more a coming).
