### ISSUE TITLE
install cargo subcommands with rust platform extension

### ISSUE THREAD

**Issue by d3m1gd** [flathub/com.visualstudio.code-oss#40]
While using `org.freedesktop.Sdk.Extension.rust-stable` from within Code OSS's terminal, trying to install cargo subcommands fails, because bin directory is a link to a read only location.

Launching following command from inside Code OSS flatpak:

```
cargo install cargo-outdated
```

Causes the following error:

```
error: Read-only file system (os error 30) at path "/home/user/.var/app/com.visualstudio.code-oss/data/cargo/bin/cargo-installxiJVhL"
```

Compilations finishes successfully, but binary can't be installed.

issue was submitted to rust-stable flatpak sdk, and was closed, indicating that it is Code OSS issue.

https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-stable/issues/59

**Comment by gasinvein** [comment]
I wonder how the directory ended up being read-only. Can you please very if `~/.var/app/com.visualstudio.code-oss/data/cargo/bin/` is indeed non-writable (e.g. by copying some file there manually) inside the sandbox?

**Comment by d3m1gd** [comment]
bin dir is actually a symlink into sdk's dir

```
sh-5.1$ ls -al /home/user/.var/app/com.visualstudio.code-oss/data/cargo/
total 4
drwxr-xr-x 1 user users 100 мая 12 11:30 .
drwxr-xr-x 1 user users  58 апр 28 15:20 ..
lrwxrwxrwx 1 user users  24 апр 22 15:54 bin -> /lib/sdk/rust-stable/bin
-rw-r--r-- 1 user users   0 мая 12 11:06 .crates2.json
-rw-r--r-- 1 user users   0 мая 12 11:06 .crates.toml
-rw-r--r-- 1 user users   0 апр 22 15:46 .package-cache
drwxr-xr-x 1 user users  26 апр 22 16:02 registry
```

```
sh-5.1$ ls -al /lib/sdk/rust-stable/
total 12
drwxr-xr-x 1 nfsnobody nfsnobody   94 мая 11 13:02 .
drwxr-xr-x 3 user      users       60 мая 12 10:46 ..
drwxr-xr-x 1 nfsnobody nfsnobody  232 янв  1  1970 bin
-rwxr-xr-x 2 nfsnobody nfsnobody   57 апр 17 11:39 enable.sh
drwxr-xr-x 1 nfsnobody nfsnobody   98 мая 11 13:02 etc
drwxr-xr-x 1 nfsnobody nfsnobody  254 янв  1  1970 lib
drwxr-xr-x 1 nfsnobody nfsnobody   52 янв  1  1970 libexec
-rw-r--r-- 2 nfsnobody nfsnobody 6475 мая 11 13:01 manifest.json
-rw-r--r-- 1 nfsnobody nfsnobody    0 мая 11 13:02 .ref
drwxr-xr-x 1 nfsnobody nfsnobody   42 янв  1  1970 share
```

i can confirm that manually creating files in that dir doesn't work, as can be seen by directory permissions. in case it is not clear, my user is not in group `nfsnobody`, nor should it be.

**Comment by gasinvein** [comment]
> bin dir is actually a symlink into sdk's dir

Is it intentional? `/usr` and `/app` are mounted read-only in flatpak sandbox, so you wouldn't be able to install anything there.

**Comment by d3m1gd** [comment]
I would like to leverage presence of rust-stable sdk and remove my cargo installation in $HOME via rustup, because they are duplicating each other.

For that i would like to be able to install custom commands as i can do in $HOME installation.

That would be perfectly possible, since $CARGO_HOME inside Code OSS flatpak is writable. Except for the bin folder, which is a symlink to ro area.

Maybe my use case is wrong, and that would be a perfectly acceptable answer.

**Comment by gasinvein** [comment]
Maybe I'm missing something, but why not just work go the default setup, why even need such symlink? The wrapper script adds `$CARGO_HOME/bin` to `$PATH` exactly for you to be able to use binaries installed via cargo.

**Comment by d3m1gd** [comment]
I am indeed using the default setup, and it is not me who installed that symlink. And I'm trying to figure out who did that.

All i did is install Code OSS flatpak along with rust-stable platform extension. That's pretty much it.

**Comment by gasinvein** [comment]
> it is not me who installed that symlink

Weird. Does it reappear if you remove it?

**Comment by d3m1gd** [comment]
Okay, so, i am awfully sorry, since apparently the link was indeed created by me. I retraced my steps by deleting Code OSS directory under ~/.var

Here is the thing: rust sdk is available from within Code OSS flatpak, but it is not in PATH, so it seems i followed some workaround from the net to symlink directly into sdk's bin dir. I am closing this issue, but it is still kinda weird that i don't get rust's sdk bin dir on my path.

**Comment by gasinvein** [comment]
> rust sdk is available from within Code OSS flatpak, but it is not in PATH

You can set `FLATPAK_ENABLE_SDK_EXT=rust-stable` to make the wrapper auto-add rust to PATH.
