### ISSUE TITLE
Pylint won't install even with flatpak-spawn terminal set up.

### ISSUE THREAD

**Issue by LifeWatcher123** [flathub/com.visualstudio.code-oss#44]
**Description**
I'm trying out this open build version, but even after setting up its terminal like so:
> {
  "terminal.integrated.profiles.linux": {
    "Linux Bash": {
      "path": "/usr/bin/flatpak-spawn",
      "args": ["--host", "--", "bash"]
    }
  },
  "terminal.integrated.defaultProfile.linux": "Linux Bash"
}

pylint through the Pylint extension won't install. Instead, it outputs the error (along with a stacktrace): 
> ModuleNotFoundError: No module named 'distutils.util'

**Steps to Reproduce:**

1. Install Code - OSS from Flathub
2. Add an integrated terminal that uses the host system's shell, in accordance with the first_run.txt file.
3. Install the `Prettier - Code formatter` extension (esbenp.prettier-vscode) and `Python` extension (ms-python.python) through the Extensions tab
4. Open a Python file so that the `pylint not installed` prompt shows up.
5. Click Install on the prompt, in which it shows the stacktrace.

Is there a possible way to make this work? I'm a fan of open builds like this, and would like to use it rather than the proprietary version.

**Comment by gasinvein** [comment]
What's the Pylint extension?

**Comment by gasinvein** [comment]
In general, if a VSCode extension needs some system package, you need to install that package in the sandbox, not on host (i.e. _without_ `flatpak-spawn --host`). Installing Python modules with `pip3 install --user` from non-flatpak-spawn terminal should work.

**Comment by LifeWatcher123** [comment]
> What's the Pylint extension? Please explain what exactly are you trying to do, step by step.

I've edited my comment to add the step by step.



> In general, if a VSCode extension needs some system package, you need to install that package in the sandbox, not on host (i.e. _without_ `flatpak-spawn --host`). Installing Python modules with `pip3 install --user` from non-flatpak-spawn terminal should work.

Thanks, I'll try this. But I'm curious as to what I should do in circumstances that the extension depends on a package installed by the Ubuntu APT, if that situation exists.

**Comment by gasinvein** [comment]
> I've edited my comment to add the step by step.

Thanks. I didn't manage to get the same `distutils.util` error, but it looks like the Install button runs `pip` wrapped in the default shell (host one in your case). So, indeed you should install it in the sandboxed shell instead. I think the easiest way to do so would be to add another shell profile without `flatpak-spawn`, open it and and run `pip3` from there.

> the extension depends on a package installed by the Ubuntu APT

Well, then things become trickier. But it's unlikely in practice for an extension to hard depend on some program/library outside pip/cargo/npm that is neither present in the flatpak SDK, nor available as an SDK extension.

**Comment by LifeWatcher123** [comment]
> So, indeed you should install it in the sandboxed shell instead. I think the easiest way to do so would be to add another shell profile without flatpak-spawn, open it and run pip3 from there.

It worked, Thanks! But trying to install `mysql` through `pip3 install mysql` doesn't work. After looking at the error messages, it seems that `/bin/sh: line 1: mysql_config: command not found` is the problematic error. Running `which mysql` inside the sandbox shell shows that it can't find it, while the host terminal can.

How should I go on with this?

**Comment by gasinvein** [comment]
> How should I go on with this?

It depends on what do you need the python mysql module for.

**Comment by LifeWatcher123** [comment]
> It depends on what do you need the python mysql module for.

It seems that it's a dependency on the `mysqlclient` python package, which I need.

**Comment by gasinvein** [comment]
But what for? Does some vscode extension depend on `mysqlclient`?

**Comment by LifeWatcher123** [comment]
> But what for? Does some vscode extension depend on `mysqlclient`?

No, I just need it to connect the application I'm making to a MySql database, and using mysqlclient is the way I know how.

**Comment by gasinvein** [comment]
Well, then I guess you can use the host shell for that, no? Packages have to be installed in the sandbox only when they're dependencies of the editor itself or its extensions.

**Comment by LifeWatcher123** [comment]
> Well, then I guess you can use the host shell for that, no? Packages have to be installed in the sandbox only when they're dependencies of the editor itself or its extensions.

If I'm understanding this right, then `mysqlclient` is a command-line app, not something that anything depends on. I'll do more research on this. Thanks! This has been enlightening.
