### ISSUE TITLE
No longer starting after latest update, last message is 'failed to find primary PersonaStore'

### ISSUE THREAD

**Issue by mlncn** [flathub/com.visualstudio.code-oss#51]
I am using "Code - OSS" available in flathub.  It says "This open source build of Visual Studio Code is not supported by Microsoft. Issues should be reported through linked bug tracker."

There was no linked bug tracker— so apologies if i've found my way to the wrong place, but if i did find the right place please do link to the bugtracker from the description!

OK, on to my error, there was an update to apply and i did, and then tried to start Code - OSS and it doesn't, no error printed to the screen (i have not yet restarted my computer to see if that helps).

The messages in syslog end with:

```
Aug  8 08:20:47 d64 com.visualstudio.code-oss.desktop[14852]: code-oss-wrapper: Setting up NPM packages
Aug  8 08:20:47 d64 com.visualstudio.code-oss.desktop[14852]: code-oss-wrapper: Setting up Cargo packages
Aug  8 08:20:47 d64 com.visualstudio.code-oss.desktop[14852]: code-oss-wrapper: Setting up Python packages
Aug  8 08:20:47 d64 gnome-contacts-[14761]: Failed to find primary PersonaStore with type ID 'eds' and ID '21188931c1ddb49ee92f86e9da78ddd11e6f5e4e'.#012Individuals will not be linked properly and creating new links between Personas will not work.#012The configured primary PersonaStore's backend may not be installed. If you are unsure, check with your distribution.
Aug  8 08:20:48 d64 kernel: [ 1131.422776] nouveau 0000:01:00.0: fb: VPR locked, but no scrubber binary!
```

**Comment by gasinvein** [comment]
> There was no linked bug tracker— so apologies if i've found my way to the wrong place, but if i did find the right place please do link to the bugtracker from the description!

This is the right bugtracker. GNOME Sofware doesn't expose "bugtracker" links currently, but hopefully will start doing so soon.

>The messages in syslog end with:

I believe `gnome-contacts` message is irrelevant. Can you please run Code-OSS from terminal and post output here?
`flatpak run com.visualstudio.code-oss//stable --wait`

**Comment by mark-chandler** [comment]
I also have this problem. Running from the command line gives the following. I waited for a few minutes, but nothing else seemed to happen. Running on Fedora 34 x86_64.
```
$ flatpak run com.visualstudio.code-oss//stable --wait

code-oss-wrapper: Setting up NPM packages
code-oss-wrapper: Setting up Cargo packages
code-oss-wrapper: Setting up Python packages
```

I've tried removing the flatpak and reinstalling it with no luck. I've since downgraded to 1.58.2 (using the method here: https://docs.flatpak.org/en/latest/tips-and-tricks.html) and that now works.
Let me know if there's anything else I can do to help diagnose the issue.

**Comment by dasebek** [comment]
I am experiencing the same problem on Fedora 34 Workstation (x86_64). The following three lines are printed and nothing else happens.
```
[david@pc4 ~]$ flatpak run com.visualstudio.code-oss//stable --wait
code-oss-wrapper: Setting up NPM packages
code-oss-wrapper: Setting up Cargo packages
code-oss-wrapper: Setting up Python packages

```

**Comment by vrutkovs** [comment]
```
$ flatpak run com.visualstudio.code-oss//stable --verbose --log debug -s 
code-oss-wrapper: Adding /app/tools/fish/bin to PATH
code-oss-wrapper: Setting up NPM packages
code-oss-wrapper: Setting up Cargo packages
code-oss-wrapper: Setting up Python packages
A JavaScript error occurred in the main process
Uncaught Exception:
Error: submitURL must be specified when uploadToServer is true
    at CrashReporter.start (electron/js2c/browser_init.js:41:472)
    at configureCrashReporter (/app/main/resources/app/out/main.js:2:1904)
    at Object.<anonymous> (/app/main/resources/app/out/main.js:1:851)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Object.<anonymous> (electron/js2c/browser_init.js:193:3237)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:193:3441)
    at __webpack_require__ (electron/js2c/browser_init.js:1:128)
    at electron/js2c/browser_init.js:1:1200
    at electron/js2c/browser_init.js:1:1267
    at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:225:10)
    at loadNativeModule (internal/modules/cjs/helpers.js:35:9)
    at Module._load (internal/modules/cjs/loader.js:747:15)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
Gtk-Message: 10:55:57.269: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:55:57.269: Failed to load module "canberra-gtk-module"
[18:0809/105557.276691:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[43:0809/105557.329206:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```

**Comment by fcabralpacheco** [comment]
Hi @gasinvein,

I had the same problem and identified the source.

The behavior of the crash reporter configuration changed [1][2]. This change causes a js error.

I found two possible solutions: 

1 - Disable the crash reporter:
```
flatpak run com.visualstudio.code-oss --disable-crash-reporter
```

2 - Configure the crash reporter directory (may be used the $XDG_CONFIG_HOME for config directory):
```
flatpak run com.visualstudio.code-oss --crash-reporter-directory="$HOME/.var/app/com.visualstudio.code-oss/config/Code - OSS/Crash Reports"
```
Since there is already a patch that changes the start command, I think it's just necessary to choose the proper solution and update the patch.

[1] https://github.com/microsoft/vscode/pull/124666
[2] https://github.com/microsoft/vscode/blob/b6ca3e52ae62b64f7e30009bed4402a0235a4e92/src/main.js#L51

**Comment by gasinvein** [comment]
This error doesn't seem to happen when running Code-OSS without full filesystem access, e..g `flatpak run --nofilesystem=host com.visualstudio.code-oss`. Strange.

**Comment by gasinvein** [comment]
Disabled crash reported until we come up with a better solution.

So sorry for pushing a broken update. I have a global `--nofilesystem=host` override, thus this bug didn't affect me and I didn't notice something isn't right.
