### ISSUE TITLE
Extensions tab is not working

### ISSUE THREAD

**Issue by jeffteixeira** [flathub/com.visualstudio.code-oss#52]
![image](https://user-images.githubusercontent.com/58240722/128724500-47be23cc-3088-4e96-b7dc-49d72449e213.png)
It is not being possible to install any extension.

**Comment by gasinvein** [comment]
Looks like [open-vsx.org](https://open-vsx.org/vscode/gallery) marketplace backend is down.

**Comment by jeffteixeira** [comment]
![image](https://user-images.githubusercontent.com/58240722/128726562-20995677-ba86-403d-9747-fb3fc9b97576.png)
But it is working on vscodium....

**Comment by gasinvein** [comment]
Oh, indeed. That's strange.

**Comment by gasinvein** [comment]
Looks like we're hitting this issue VSCodium/vscodium#746. I guess we need to port the fix from VSCodium.

**Comment by jeffteixeira** [comment]
I believe so...

**Comment by gasinvein** [comment]
In the meantime, you can manually apply workaround from https://github.com/VSCodium/vscodium/issues/746#issuecomment-881049046

**Comment by jeffteixeira** [comment]
![image](https://user-images.githubusercontent.com/58240722/128736352-03b0832c-3609-4778-8fcd-84ef10c027aa.png)
I made two changes to the `~/.vscode-oss/argv.json` file: I changed `enable-crash-reporter` to `false`(https://github.com/flathub/com.visualstudio.code-oss/issues/51#issuecomment-895094559) and added the line `"enable-browser-code-loading": false`. The extensions tab is working again.

**Comment by vilgotf** [comment]
Think this is fixed

**Comment by gasinvein** [comment]
I believe this is resolved. Reopen if still occurs for you.
